/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2024 HaringPro
	Apache License 2.0

	Pass: Post-processing compositing

--------------------------------------------------------------------------------
*/

//======// Input //===============================================================================//

layout (local_size_x = 16, local_size_y = 16) in;
const vec2 workGroupsRender = vec2(1.0, 1.0);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

#define TONE_MAPPER AgX_Minimal // [None AcademyFit AcademyFull AgX_Minimal AgX_Full Lottes GT GT7]

#define BLOOM_INTENSITY 1.0 // Intensity of bloom. [0.0 0.01 0.02 0.05 0.07 0.1 0.15 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0 3.0 4.0 5.0 7.0 10.0 15.0 20.0]
#define BLOOMY_FOG_INTENSITY 1.0 // Intensity of bloomy fog. [0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.75 0.8 0.9 1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0 2.5 3.0 3.5 4.0 5.0]

#define PURKINJE_SHIFT // Enables purkinje shift effect
#define PURKINJE_SHIFT_STRENGTH 0.3 // Strength of purkinje shift effect. [0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0]

// #define VIGNETTE_ENABLED // Enables vignetting effect
#define VIGNETTE_STRENGTH 1.0 // Strength of vignetting effect. [0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0 2.5 3.0 3.5 4.0 5.0]
#define VIGNETTE_ROUNDNESS 0.5 // Roundness of vignetting effect. [0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0 2.5 3.0 3.5 4.0 5.0]

//======// Uniform //=============================================================================//

writeonly uniform image2D colorimg8; // LDR output

#include "/lib/universal/Uniform.glsl"

//======// SSBO //================================================================================//

#include "/lib/universal/SSBO.glsl"

//======// Function //============================================================================//

const vec2 bloomTileOffset[6] = vec2[6](
	vec2(0.0000, 0.0000),
	vec2(0.0000, 0.5000),
	vec2(0.2500, 0.5000),
	vec2(0.2500, 0.6250),
	vec2(0.3125, 0.6250),
	vec2(0.3150, 0.6563)
);

void CombineBloomAndFog(inout vec3 scene, in ivec2 texel, in float exposure) {
	vec3 bloomData = vec3(0.0);
	vec2 screenCoord = texelToUv(texel);

	float weight = 1.0;
	float sumWeight = 0.0;

	vec2 upscalingCoord = screenCoord;
	for (uint i = 0u; i < 6u; ++i) {
		upscalingCoord *= 0.5;
    	vec2 sampleCoord = upscalingCoord + bloomTileOffset[i];
		sampleCoord += viewPixelSize * float(i * 8);
		vec3 sampleTile = textureBicubic(colortex4, sampleCoord).rgb;

		bloomData += sampleTile * weight;
		sumWeight += weight;
		weight *= 0.9;
	}

	bloomData *= rcp(sumWeight);

	float bloomIntensity = BLOOM_INTENSITY * 0.25;
	bloomIntensity /= max(exposure, 1.0) + 1.0;

	scene = (scene + bloomData * bloomIntensity) / (1.0 + bloomIntensity * 0.5);

	#ifdef BLOOMY_FOG
		float mask = saturate(texelFetch(colortex12, texel, 0).x);
		scene = mix(bloomData, scene, mix(1.0, mask, BLOOMY_FOG_INTENSITY));
	#endif

	if (rainStrength > 1e-2) {
		float rainAlpha = texture(colortex6, screenCoord).a;
		rainAlpha = oms(rainAlpha) * RAIN_VISIBILITY;
		scene = scene * oms(rainAlpha) + bloomData * rainAlpha * 1.25;
	}
}

// See section 3.4 of http://www.diva-portal.org/smash/get/diva2:24136/FULLTEXT01.pdf
vec3 ScotopicVision(in vec3 color, in float exposure) {
	const vec3 rodResponse = vec3(0.05, 0.55, 0.60);

	vec3 xyz = color * sRGB_2_XYZ;
	vec3 scotopic = xyz * max0(1.33 * (1.0 + (xyz.y + xyz.z) / xyz.x) - 1.68);

	float rodLuminance = dot(scotopic * XYZ_2_sRGB, rodResponse);
	float mesopicFactor = saturate(log2(1.0 + exposure) / (2.0 + 4.0 * rodLuminance));
	return mix(color, rodLuminance * vec3(0.56, 0.78, 1.0), PURKINJE_SHIFT_STRENGTH * mesopicFactor);
}

vec3 None(in vec3 x) {
	return x;
}

// Lottes 2016, "Advanced Techniques and Optimization of HDR Color Pipelines"
// https://gpuopen.com/wp-content/uploads/2016/03/GdcVdrLottes.pdf
vec3 Lottes(in vec3 x) {
	x *= 2.0;

	const vec3 a      = vec3(1.35);
	const vec3 d      = vec3(0.92);
	const vec3 hdrMax = vec3(8.0);
	const vec3 midIn  = vec3(0.2);
	const vec3 midOut = vec3(0.3);

	const vec3 ad = a * d;
	const vec3 curvedMidIn = pow(midIn, a);
	const vec3 curvedHdrMax = pow(hdrMax, a);
	const vec3 b = -curvedMidIn + curvedHdrMax * midOut;
	const vec3 c = pow(hdrMax, ad) * curvedMidIn - curvedHdrMax * pow(midIn, ad) * midOut;

	return sRGBToLinear(pow(x, a) * (pow(hdrMax, ad) - pow(midIn, ad)) * midOut / (pow(x, ad) * b + c));
}

#include "/lib/post/ACES.glsl"
#include "/lib/post/AgX.glsl"
#include "/lib/post/GT.glsl"

//======// Main //================================================================================//
void main() {
    uvec2 localPos = QuadLayout16x16(gl_LocalInvocationIndex);
    ivec2 texelPos = ivec2(localPos + gl_WorkGroupID.xy * gl_WorkGroupSize.xy);

 	#if EXPOSURE_MODE == MANUAL
		float exposure = exp2(-MANUAL_EV);
	#else
		float exposure = exposure.value;
	#endif

	#ifdef MOTION_BLUR
		vec3 color = texelFetch(colortex0, texelPos, 0).rgb;
	#else
		vec3 color = texelFetch(colortex1, texelPos, 0).rgb;
	#endif

	// Bloom and fog
	#ifdef BLOOM
		CombineBloomAndFog(color, texelPos, exposure);
	#endif

	// Debug sky environment map
	#ifdef DEBUG_SKY_MAP
		if (all(lessThan(texelPos, skyMapRes))) {
			color = texelFetch(skyMapTex, texelPos, 0).rgb;
		}
	#endif

	// Apply exposure
	color *= exposure;

	// Purkinje shift
	#ifdef PURKINJE_SHIFT
		color = ScotopicVision(color, exposure);
	#endif

	// Vignetting
	#ifdef VIGNETTE_ENABLED
		vec2 ndcCoord = texelToUv(texelPos) * 2.0 - 1.0;
		ndcCoord.x *= mix(1.0, aspectRatio, VIGNETTE_ROUNDNESS);
		color *= exp2(-0.5 * VIGNETTE_STRENGTH * sdot(ndcCoord));
	#endif

	// Apply DRT
	{
		// Working to DRT space
		// color *= sRGB_2_Rec2020;

		// Tone mapping
		color = TONE_MAPPER(color);

		// DRT to working space
		// color *= Rec2020_2_sRGB;

		// Working to display space
		color = saturate(linearToSRGB(color));
	}

	// Debug tone mapping plot
	#ifdef DEBUG_TONE_MAPPING_PLOT
		const float scale = 1.5;

		vec2 uv = texelToUv(texelPos) * vec2(aspectRatio, 1.0) * scale;
		float plot = smoothstep(0.0, scale * viewPixelSize.y, abs(uv.y - TONE_MAPPER(vec3(uv.x)).x));

		// Show LDR range
		color = vec3(0.25) * step(uv.x, 1.0);
		color = mix(vec3(1.0), color, plot);
	#endif

	imageStore(colorimg8, texelPos, vec4(color, 1.0));
}