/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2024 HaringPro
	Apache License 2.0

	Pass: Compute translucent specular lighting & water fog

--------------------------------------------------------------------------------
*/

#define PASS_TRANSLUCENT

//======// Input //===============================================================================//

layout (local_size_x = 16, local_size_y = 16) in;
const vec2 workGroupsRender = vec2(1.0, 1.0);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

layout (r11f_g11f_b10f) restrict uniform image2D colorimg0; // Scene data
writeonly uniform image2D colorimg1; // Specular lighting output

#include "/lib/universal/Uniform.glsl"

//======// SSBO //================================================================================//

#include "/lib/universal/SSBO.glsl"

//======// Struct //==============================================================================//

#include "/lib/universal/Material.glsl"

//======// Function //============================================================================//

#include "/lib/universal/Transform.glsl"
#include "/lib/universal/Fetch.glsl"
#include "/lib/universal/Random.glsl"

#include "/lib/atmosphere/Common.glsl"
#ifdef CLOUD_SHADOWS
	#include "/lib/atmosphere/clouds/Shadows.glsl"
#endif

#include "/lib/water/WaterFog.glsl"

#include "/lib/lighting/Common.glsl"
#include "/lib/lighting/Shadows.glsl"

#include "/lib/surface/ScreenSpaceRaytracer.glsl"

vec4 CalculateSpecularReflections(in vec3 screenPos, in vec3 viewPos, in vec3 worldNormal, in vec3 worldDir, in float dither, in float skylight, in bool waterMask) {
	float NdotV = abs(dot(worldNormal, worldDir));
	vec3 rayDir = worldDir + worldNormal * NdotV * 2.0;

	if (dot(worldNormal, rayDir) < EPS) return vec4(0.0);

	vec3 reflection = vec3(0.0);
	if (skylight > 1e-3 && (isEyeInWater == 0 || !waterMask)) {
		vec2 skyViewCoord = FromSkyViewLutParams(rayDir) + vec2(0.0, 0.5);
		vec3 skyRadiance = textureBicubic(skyViewTex, skyViewCoord).rgb;

		skylight = remap(0.3, 0.7, cube(skylight));
		reflection = skyRadiance * skylight;
	}

	float ior = waterMask ? isEyeInWater == 1 ? 1.0 / WATER_REFRACT_IOR : WATER_REFRACT_IOR : GLASS_REFRACT_IOR;
	float fresnel = FresnelDielectricN(NdotV, ior);
	uint raySteps = uint(RAYTRACE_SAMPLES * (fresnel * 0.5 + 0.5));

	if (ScreenSpaceRaytrace(viewPos, mat3(gbufferModelView) * rayDir, dither, raySteps, screenPos)) {
		screenPos.xy *= viewPixelSize;
		float edgeFade = screenPos.x * screenPos.y * oms(screenPos.x) * oms(screenPos.y);
		edgeFade *= 1e2 + cube(saturate(1.0 - gbufferModelViewInverse[2].y)) * 4e3;
		reflection += (texture(colortex4, screenPos.xy * 0.5).rgb - reflection) * saturate(edgeFade);
	}

	return satU16f(vec4(reflection * fresnel, fresnel));
}

//======// Main //================================================================================//
void main() {
    ivec2 screenTexel = ivec2(gl_GlobalInvocationID.xy);
	uvec4 gbufferData0 = loadGbufferData0(screenTexel);

	// Skip opaque fragments
	if (clamp(gbufferData0.y, 2u, 3u) != gbufferData0.y) return;

	float depth = loadDepth0(screenTexel);
	vec3 screenPos = vec3(texelToUv(screenTexel), depth);
	vec3 viewPos = ScreenToViewSpace(screenPos);
	#if defined DISTANT_HORIZONS
		if (depth > 1.0 - EPS) {
			depth = screenPos.z = loadDepth0DH(screenTexel);
			viewPos = ScreenToViewSpaceDH(screenPos);
		}
	#endif

	vec3 worldPos = mat3(gbufferModelViewInverse) * viewPos;
	float worldDistSquared = sdot(worldPos);
	vec3 worldDir = worldPos * inversesqrt(worldDistSquared);
	worldPos += gbufferModelViewInverse[3].xyz;

	vec2 waterData = Unpack2x8(texelFetch(colortex12, screenTexel, 0).x);
	bool waterMask = waterData.x > 0.0;

	// Water fog
	if (waterMask && isEyeInWater == 0) {
		mat2x3 waterFog = AnalyticWaterFog(waterData.y, waterData.x * 64.0, dot(worldLightVector, worldDir));

		vec3 sceneOut = ApplyFog(imageLoad(colorimg0, screenTexel).rgb, waterFog);

		// Skybox reflection for occluded water
		if (gbufferData0.y == 2u) {
			vec3 worldNormal = OctDecodeUnorm(Unpack2x8(texelFetch(colortex12, screenTexel, 0).y));

			float NdotV = abs(dot(worldNormal, worldDir));
			vec3 rayDir = worldDir + worldNormal * NdotV * 2.0;

			vec2 skyViewCoord = FromSkyViewLutParams(rayDir) + vec2(0.0, 0.5);
			vec3 skyRadiance = textureBicubic(skyViewTex, skyViewCoord).rgb;

			vec3 reflection = skyRadiance * remap(0.3, 0.7, cube(waterData.y));
			float fresnel = FresnelDielectricN(NdotV, WATER_REFRACT_IOR);

			sceneOut = mix(sceneOut, reflection, fresnel);
		}

		imageStore(colorimg0, screenTexel, vec4(sceneOut, 1.0));
	}

	//============================================================================================//

	// Specular lighting
	float skyLightmap = Unpack2x8UY(gbufferData0.x);
	vec3 worldNormal = FetchWorldNormal(gbufferData0.w);

	float dither = SampleStbnVec1(screenTexel, frameCounter + 4);
	vec4 specularOut = CalculateSpecularReflections(screenPos, viewPos, worldNormal, worldDir, dither, skyLightmap, waterMask);

	// Cloud shadows
	#ifdef CLOUD_SHADOWS
		vec2 cloudShadowCoord = WorldToCloudShadowScreenPos(worldPos).xy;
		float cloudShadow = textureBicubic(cloudShadowTex, saturate(cloudShadowCoord)).x;
	#else
		float cloudShadow = 1.0 - wetness * 0.96;
	#endif

	// Sunlight
	vec3 sunlightMult = cloudShadow * saturate(skyLightmap * 1e6) * global.light.directIlluminance;
	float NdotL = dot(worldNormal, worldLightVector);

	// Direct specular lighting
	if (NdotL > 1e-3) {
		float distortionFactor;

		vec3 flatNormal = FetchFlatNormal(gbufferData0);
		vec3 normalOffset = flatNormal * (worldDistSquared * 1e-4 + 3e-2) * (2.0 - saturate(NdotL));
		vec3 shadowScreenPos = WorldToShadowScreenSpace(worldPos + normalOffset, distortionFactor);

		if (saturate(shadowScreenPos) == shadowScreenPos) {
			float blockerSearch = BlockerSearch(shadowScreenPos, dither, 0.5 * distortionFactor);
			shadowScreenPos.z -= (worldDistSquared * 1e-9 + 3e-6) * (1.0 + dither) / distortionFactor * shadowDistance;

			vec3 shadow = PercentageCloserFilter(shadowScreenPos, worldPos, dither, 0.5 * blockerSearch * distortionFactor);

			if (dot(shadow, vec3(1.0)) > EPS) {
				float NdotV = abs(dot(worldNormal, worldDir));
				vec3 halfway = normalize(worldLightVector - worldDir);
				float NdotH = dot(worldNormal, halfway);
				float LdotH = dot(worldLightVector, halfway);

				shadow = saturate(shadow) * sunlightMult;

				float f0 = F0FromIOR(waterMask ? WATER_REFRACT_IOR : GLASS_REFRACT_IOR);
				specularOut.rgb += shadow * SpecularGGX(LdotH, NdotV, NdotL, NdotH, TRANSLUCENT_ROUGHNESS, vec3(f0));
			}
		}
	}

	imageStore(colorimg1, screenTexel, specularOut);
}